version: '{build}'

image: Visual Studio 2015

cache:
  - NimBinaries
  - p2pdCache

matrix:
  # We always want 32 and 64-bit compilation
  fast_finish: false

platform:
  - x86
  - x64

# when multiple CI builds are queued, the tested commit needs to be in the last X commits cloned with "--depth X"
clone_depth: 10

install:
  - git submodule update --init --recursive

  # use the newest versions documented here: https://www.appveyor.com/docs/windows-images-software/#mingw-msys-cygwin
  - IF "%PLATFORM%" == "x86" SET PATH=C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin;%PATH%
  - IF "%PLATFORM%" == "x64" SET PATH=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;%PATH%

  # build nim from our own branch - this to avoid the day-to-day churn and
  # regressions of the fast-paced Nim development while maintaining the
  # flexibility to apply patches
  - curl -O -L -s -S https://raw.githubusercontent.com/status-im/nimbus-build-system/master/scripts/build_nim.sh
  - env MAKE="mingw32-make -j2" ARCH_OVERRIDE=%PLATFORM% bash build_nim.sh Nim csources dist/nimble NimBinaries
  - SET PATH=%CD%\Nim\bin;%PATH%

  # set path for produced Go binaries
  - MKDIR goblin
  - CD goblin
  - SET GOPATH=%CD%
  - SET PATH=%GOPATH%\bin;%PATH%
  - CD ..

  # install and build go-libp2p-daemon
  - bash scripts/build_p2pd.sh p2pdCache v0.3.0

build_script:
  - nimble install -y --depsOnly

test_script:
  - nimble test
  - nimble examples_build

deploy: off

