global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "apps"
    static_configs:
      - targets:
          - nim-libp2p-quic-1:8008
          - nim-libp2p-quic-2:8008
          - nim-libp2p-quic-3:8008
          - nim-libp2p-quic-4:8008
          - nim-libp2p-quic-5:8008
          - nim-libp2p-quic-6:8008
          - nim-libp2p-quic-7:8008
          - nim-libp2p-quic-8:8008
          - nim-libp2p-quic-9:8008
          - nim-libp2p-quic-10:8008
          - nim-libp2p-quic-11:8008
          - nim-libp2p-quic-12:8008
          - nim-libp2p-quic-13:8008
          - nim-libp2p-quic-14:8008
          - nim-libp2p-quic-15:8008
          - nim-libp2p-quic-16:8008
          - nim-libp2p-quic-17:8008
          - nim-libp2p-quic-18:8008
          - nim-libp2p-quic-19:8008
          - nim-libp2p-quic-20:8008
          - nim-libp2p-quic-21:8008
          - nim-libp2p-quic-22:8008
          - nim-libp2p-quic-23:8008
          - nim-libp2p-quic-24:8008
          - nim-libp2p-quic-25:8008
          - nim-libp2p-quic-26:8008
          - nim-libp2p-quic-27:8008
          - nim-libp2p-quic-28:8008
          - nim-libp2p-quic-29:8008
          - nim-libp2p-quic-30:8008
          - nim-libp2p-quic-31:8008
          - nim-libp2p-quic-32:8008
          - nim-libp2p-quic-33:8008
          - nim-libp2p-quic-34:8008
          - nim-libp2p-quic-35:8008
          - nim-libp2p-quic-36:8008
          - nim-libp2p-quic-37:8008
          - nim-libp2p-quic-38:8008
          - nim-libp2p-quic-39:8008
          - nim-libp2p-quic-40:8008
          - nim-libp2p-quic-41:8008
          - nim-libp2p-quic-42:8008
          - nim-libp2p-quic-43:8008
          - nim-libp2p-quic-44:8008
          - nim-libp2p-quic-45:8008
          - nim-libp2p-quic-46:8008
          - nim-libp2p-quic-47:8008
          - nim-libp2p-quic-48:8008
          - nim-libp2p-quic-49:8008
          - nim-libp2p-quic-50:8008
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
