name: daily-common

on:
  workflow_call:
    inputs:
      nim-branch:
        description: 'Nim branch'
        required: true
        type: string
      platform:
        description: 'Platform'
        required: true
        type: string
      extra:
        description: 'Include Extra'
        required: true
        type: string

jobs:
  delete-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: snnaplab/delete-branch-cache-action@v1

  build:
    needs: delete-cache
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(inputs.platform) }}
        branch: ${{ fromJSON(inputs.nim-branch) }}
        include: ${{ fromJSON(inputs.extra) }}

    defaults:
      run:
        shell: ${{ matrix.shell }}

    name: '${{ matrix.target.os }}-${{ matrix.target.cpu }} (Nim ${{ matrix.branch }})'
    runs-on: ${{ matrix.builder }}
    continue-on-error: ${{ matrix.branch == 'devel' || matrix.branch == 'version-2-0' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nim
        uses: "./.github/actions/install_nim"
        with:
          os: ${{ matrix.target.os }}
          shell: ${{ matrix.shell }}
          nim_branch: ${{ matrix.branch }}
          cpu: ${{ matrix.target.cpu }}

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '~1.15.5'
          cache: false

      - name: Install p2pd
        run: |
          V=1 bash scripts/build_p2pd.sh p2pdCache 124530a3

      - name: Run tests
        run: |
          nim --version
          nimble --version
          nimble install -y --depsOnly
          NIMFLAGS="${NIMFLAGS} --mm:refc" nimble test
          if [[ "${{ matrix.branch }}" == "devel" ]]; then
            echo -e "\nTesting with '--mm:orc':\n"
            NIMFLAGS="${NIMFLAGS} --mm:orc" nimble test
          fi
