name: daily-common

on:
  workflow_call:
    inputs:
      nim-branch:
        description: 'Nim branch'
        required: true
        type: string
      cpu:
        description: 'CPU'
        required: true
        type: string

jobs:
  delete-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: snnaplab/delete-branch-cache-action@v1

  build:
    needs: delete-cache
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: linux
            builder: ubuntu-20
            shell: bash
          - os: macos
            builder: macos-12
            shell: bash
          - os: windows
            builder: windows-2019
            shell: msys2 {0}
        branch: ${{ fromJSON(inputs.nim-branch) }}
        cpu: ${{ fromJSON(inputs.cpu) }}
        exclude: ${{ fromJSON(inputs.excludes) }}

    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    name: '${{ matrix.platform.os }}-${{ matrix.cpu }} (Nim ${{ matrix.branch }})'
    runs-on: ${{ matrix.platform.builder }}
    continue-on-error: ${{ matrix.branch == 'devel' || matrix.branch == 'version-2-0' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nim
        uses: "./.github/actions/install_nim"
        with:
          os: ${{ matrix.platform.os }}
          shell: ${{ matrix.platform.shell }}
          nim_branch: ${{ matrix.branch }}
          cpu: ${{ matrix.cpu }}

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '~1.15.5'
          cache: false

      - name: Install p2pd
        run: |
          V=1 bash scripts/build_p2pd.sh p2pdCache 124530a3

      - name: Run tests
        run: |
          nim --version
          nimble --version
          nimble install -y --depsOnly
          NIMFLAGS="${NIMFLAGS} --mm:refc" nimble test
          if [[ "${{ matrix.branch }}" == "devel" ]]; then
            echo -e "\nTesting with '--mm:orc':\n"
            NIMFLAGS="${NIMFLAGS} --mm:orc" nimble test
          fi
