name: NBC Bump PR

on: [push, pull_request]

jobs:
  bumpNBC:
    runs-on: ubuntu-latest
    steps:
      # - name: Clone nim-libp2p
      #   uses: actions/checkout@v2
      #   with:
      #     path: nim-libp2p
      #     submodules: true
      #     fetch-depth: 0
        
      - name: Clone NBC
        uses: actions/checkout@v2
        with:
          repository: status-im/nim-beacon-chain
          ref: devel
          path: nbc
          submodules: true
          fetch-depth: 0
      
      - name: Checkout this ref
        run: |
          cd nbc/vendor/nim-libp2p
          git checkout $GITHUB_SHA

      - name: Commit this bump
        run: |
          cd nbc
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name = "${{ github.actor }}"
          git commit -a -m "auto-bump nim-libp2p"
      
      - name: Make PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: nim-libp2p-auto-bump
          path: nbc


